### ISSUE TITLE
Latest docker image did not work

### ISSUE THREAD

**Issue by BrianLakstins** [opensensor/lightNVR#67]
I had it working earlier today with 0.12.4.

I reloaded latest and the web interface shows 404.

Logs show this:

```
[2025-10-30 17:48:42] [INFO] Received request: uri=/, method=GET
[2025-10-30 17:48:42] [INFO] Root path detected, web_root=/var/lib/lightnvr/www
[2025-10-30 17:48:42] [INFO] No Authorization header found for URI: /, checking for cookies
[2025-10-30 17:48:42] [INFO] No Cookie header found
[2025-10-30 17:48:42] [INFO] Authentication failed for request: /
[2025-10-30 17:48:42] [INFO] Serving / without authentication
[2025-10-30 17:48:42] [INFO] Root path detected in main handler, redirecting to index.html
[2025-10-30 17:48:42] [INFO] Index file not found, redirecting to /index.html
```

I reverted back to 0.12.4 and it worked fine.

If there was a breaking change and I need to clear out all stored data, I can do that.

My setup, in case anything about it could be interfering with the user interface working with the latest build.

1. Windows 11 Host system with Hyper-V
2. Ubuntu 2404 VM running under Hyper-V (basically it's own computer)
3. Docker running in Ubuntu 2404 VM (command line type stuff)
4. Portainer running on Docker (also running from command line)
5. Traefik running as a stack in Portainer (web interface management)
6. LightNVR running as a stack in Portainer (web interface management)
7. Config and Data volumes mapped to a NAS through NFS (as mapped in docker-compose.yaml)
8. RTSP Cameras on separate IOT subnet that has restricted access to local network where server is running (nothing Internet here, just separate networks with routers in between to prevent and bad IOT actors from accessing anything local).

**Comment by BrianLakstins** [comment]
Good news: Recorded streams still match what they should for 0.12.4, and I got some video of interesting visitors for trick or treat last night (we have it on the 30th and 31st - don't know why, but I'm fine with it)

https://photo.lakstins.net/share/e2P-Tv2vuxqgdnyrglf_JtqE4D1BTwL9S3HRBaBLgnE5vTZl-qtKyOMibDDPnizlGw8

Bad news: 0.13 is still not giving me a web interface.  I tried without the proxy and it did not work that way either.

Here are some DEBUG level logs.

```
[2025-10-31 13:50:37] [DEBUG] New connection accepted
6b534a5a 3 mongoose.c:9167:read_conn    4 12 0:0:0 78 err 0
[2025-10-31 13:50:37] [INFO] Received request: uri=/, method=GET
[2025-10-31 13:50:37] [INFO] Root path detected, web_root=/var/lib/lightnvr/www
[2025-10-31 13:50:37] [INFO] No Authorization header found for URI: /, checking for cookies
[2025-10-31 13:50:37] [INFO] No Cookie header found
[2025-10-31 13:50:37] [DEBUG] No Authorization header or valid cookies found
[2025-10-31 13:50:37] [INFO] Authentication failed for request: /
[2025-10-31 13:50:37] [INFO] Serving / without authentication
[2025-10-31 13:50:37] [INFO] Root path detected in main handler, redirecting to index.html
[2025-10-31 13:50:37] [INFO] Index file not found, redirecting to /index.html
6b534a5a 3 mongoose.c:9177:write_conn   4 12 snd 64/16384 rcv 0/16384 n=64 err=0
6b534a5a 3 mongoose.c:9167:read_conn    4 12 0:0:0 -1 err 2
[2025-10-31 13:50:37] [DEBUG] Connection closed
[2025-10-31 13:50:37] [DEBUG] Connection closed and cleaned up
```

**Comment by BrianLakstins** [comment]
v0.13.0 configured with 1 stream.

I did not alter the lightnvr.ini file.

My docker-compose.yml file.

```
services:
  lightnvr:
    image: ghcr.io/opensensor/lightnvr:latest
    container_name: lightnvr-dev
    restart: unless-stopped
    ports:
      - 1984:1984/tcp   # go2rtc API port
      - 8090:8080
    volumes:
      - config:/etc/lightnvr
      - data:/var/lib/lightnvr/data
    networks:
      - portainer_default         
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lightnvr-dev.rule=Host(`lightnvr-dev.${SystemId}.${SystemLocation}.dns9.co`)"
      - "traefik.http.routers.lightnvr-dev.entrypoints=ep-http"
      - "traefik.http.routers.lightnvr-dev-secure.rule=Host(`lightnvr-dev.${SystemId}.${SystemLocation}.dns9.co`)"
      - "traefik.http.routers.lightnvr-dev-secure.entrypoints=ep-https"
      - "traefik.http.routers.lightnvr-dev-secure.tls.certresolver=cr1"
      - "traefik.http.routers.lightnvr-dev-secure.tls=true"
      - "traefik.http.routers.lightnvr-dev-secure.service=lightnvr-dev"

      - "traefik.http.services.lightnvr-dev.loadbalancer.server.port=8080"
      - "traefik.docker.network=portainer_default"

networks:
  portainer_default:
    external: true 
    
volumes:
  config:
      driver_opts:
        type: "nfs"
        o: "nfsvers=4,addr=${IpAddressNFS},rw"
        device: ":/${NFSVolumePath}/${SystemId}/lightnvr-dev-config" 

  data:
      driver_opts:
        type: "nfs"
        o: "nfsvers=4,addr=${IpAddressNFS},rw"
        device: ":/${NFSVolumePath}/${SystemId}/lightnvr-dev-data"  
```

Recordings, Streams, Motion, Settings, Users, and System tabs are very responsive.

Live view shows a loading and eventual time out.

Post event to /api/webrtc?src=Doorbell gives a 404 error.

Click the "HLS View" button and video comes right up (seems to be delayed a few minutes and eventually just stops).

Restarted container.  Everything that was working is still working.

Post event to /api/webrtc?src=Doorbell gives a 500 error now.

Change to debug level logging and restart container again.

Getting 404 error again for /api/webrtc?src=Doorbell

Logs that mention WebRTC

```
[INFO] WebRTC Port: 8555 (TCP/UDP)
14:39:34.415 INF [webrtc] listen addr=:8555
web_port=8080 web_root=/var/lib/lightnvr/web web_auth_enabled=true web_username=admin webrtc_disabled=false web_password=******** storage_path=/var/lib/lightnvr/data/recordings storage_path_hls= max_storage_size=0 retention_days=30 auto_delete_oldest=true max_streams=16 log_file=/var/log/lightnvr/lightnvr.log log_level=3 pid_file=/var/run/lightnvr.pid db_path=/var/lib/lightnvr/data/database/lightnvr.db models_path=/var/lib/lightnvr/data/models buffer_size=1024 use_swap=true swap_size=128
[2025-10-31 14:40:30] [INFO] Received request: uri=/api/webrtc, method=POST
[2025-10-31 14:40:30] [INFO] API request received: POST /api/webrtc, threading=enabled
[2025-10-31 14:40:30] [DEBUG] Route matched: method=POST, pattern=/api/webrtc, uri=/api/webrtc
[2025-10-31 14:40:30] [INFO] API route matched: POST /api/webrtc
[2025-10-31 14:40:30] [INFO] Handler has opted out of auto-threading: POST /api/webrtc
[2025-10-31 14:40:30] [INFO] Handling API request directly: POST /api/webrtc
[2025-10-31 14:40:30] [INFO] Processing WebRTC offer request
[2025-10-31 14:40:30] [INFO] Handling POST /api/webrtc request
[2025-10-31 14:40:30] [INFO] Request URI: /api/webrtc
[2025-10-31 14:40:30] [INFO] WebRTC offer length: 6036
[2025-10-31 14:40:30] [INFO] WebRTC offer preview: {"type":"offer","sdp":"v=0\r\no=- 5879450494452044976 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:
[2025-10-31 14:40:30] [INFO] Successfully handled WebRTC offer request for stream: Doorbell
[2025-10-31 14:40:30] [INFO] Completed WebRTC offer request
web_port=8080 web_root=/var/lib/lightnvr/web web_auth_enabled=true web_username=admin webrtc_disabled=false web_password=******** storage_path=/var/lib/lightnvr/data/recordings storage_path_hls= max_storage_size=0 retention_days=30 auto_delete_oldest=true max_streams=16 log_file=/var/log/lightnvr/lightnvr.log log_level=3 pid_file=/var/run/lightnvr.pid db_path=/var/lib/lightnvr/data/database/lightnvr.db models_path=/var/lib/lightnvr/data/models buffer_size=1024 use_swap=true swap_size=128
[2025-10-31 14:41:22] [INFO] Received request: uri=/api/webrtc, method=POST
[2025-10-31 14:41:22] [INFO] API request received: POST /api/webrtc, threading=enabled
[2025-10-31 14:41:22] [DEBUG] Route matched: method=POST, pattern=/api/webrtc, uri=/api/webrtc
[2025-10-31 14:41:22] [INFO] API route matched: POST /api/webrtc
[2025-10-31 14:41:22] [INFO] Handler has opted out of auto-threading: POST /api/webrtc
[2025-10-31 14:41:22] [INFO] Handling API request directly: POST /api/webrtc
[2025-10-31 14:41:22] [INFO] Processing WebRTC offer request
[2025-10-31 14:41:22] [INFO] Handling POST /api/webrtc request
[2025-10-31 14:41:22] [INFO] Request URI: /api/webrtc
[2025-10-31 14:41:22] [INFO] WebRTC offer length: 6036
[2025-10-31 14:41:22] [INFO] WebRTC offer preview: {"type":"offer","sdp":"v=0\r\no=- 4912151252922577993 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:
[2025-10-31 14:41:22] [INFO] Successfully handled WebRTC offer request for stream: Doorbell
[2025-10-31 14:41:22] [INFO] Completed WebRTC offer request
```

**Comment by BrianLakstins** [comment]
A few changes from the default in your ini file.

Main one seems to be the binary_path for go2rtc.

What is the external_ip value?  Is that the docker container's ip address?

**Comment by BrianLakstins** [comment]
I created a new docker-compose,yml file based on your latest.

Only changes.  Let me know if they would break any functionality.
1. Uses named volumes on my NAS through NFS
2. Uses Traefik labels to reverse proxy the web interface

```
services:
  lightnvr:
    image: ghcr.io/opensensor/lightnvr:latest
    container_name: lightnvr-latest
    restart: unless-stopped
    ports:
      #- "8080:8080"     # Web UI
      - "8554:8554"     # RTSP
      - "8555:8555"     # WebRTC TCP
      - "8555:8555/udp" # WebRTC UDP
      - "1984:1984"     # go2rtc API
    volumes:
      # Only mount what needs persistence
      # DO NOT mount /var/lib/lightnvr directly - it will overwrite web assets!
      - config:/etc/lightnvr
      - data:/var/lib/lightnvr/data
    environment:
      # Timezone configuration
      - TZ=UTC  # Change to your timezone (e.g., America/New_York, Europe/London)

      # go2rtc configuration persistence
      # Set to 'false' to let go2rtc regenerate config on each restart
      - GO2RTC_CONFIG_PERSIST=true

      # Auto-initialize configuration files on first run
      - LIGHTNVR_AUTO_INIT=true
    env_file:
      - stack.env
    networks:
      - portainer_default         
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lightnvr-latest.rule=Host(`lightnvr-latest.${SystemId}.${SystemLocation}.dns9.co`)"
      - "traefik.http.routers.lightnvr-latest.entrypoints=ep-http"
      - "traefik.http.routers.lightnvr-latest-secure.rule=Host(`lightnvr-latest.${SystemId}.${SystemLocation}.dns9.co`)"
      - "traefik.http.routers.lightnvr-latest-secure.entrypoints=ep-https"
      - "traefik.http.routers.lightnvr-latest-secure.tls.certresolver=cr1"
      - "traefik.http.routers.lightnvr-latest-secure.tls=true"
      - "traefik.http.routers.lightnvr-latest-secure.service=lightnvr-latest"

      - "traefik.http.services.lightnvr-latest.loadbalancer.server.port=8080"
      - "traefik.docker.network=portainer_default"

networks:
  portainer_default:
    external: true 
    
volumes:
  config:
      driver_opts:
        type: "nfs"
        o: "nfsvers=4,addr=${IpAddressNFS},rw"
        device: ":/${NFSVolumePath}/${SystemId}/lightnvr-latest-config" 

  data:
      driver_opts:
        type: "nfs"
        o: "nfsvers=4,addr=${IpAddressNFS},rw"
        device: ":/${NFSVolumePath}/${SystemId}/lightnvr-latest-data"  

```

Initial web interface shows an "Error loading streams: Request timed out".  There are 401 errors to /api/settings and /api/streams showing in the debug network console.

I hit logout and then log in as user admin.

index.html comes up with a "No streams configured" message and a "Configure Streams" button.

Added one stream named "Porch"

Go to "Live View" tab.

Getting 404 error in debug network console for /api/webrtc?src=Porch.

Click HLS View.  I see the Portch camera.

**Comment by matteius** [comment]
I just published a new container -- maybe check that one?   I haven't been able to reproduce the issue with webRTC.

**Comment by BrianLakstins** [comment]
I do use mixed case.  Kitchen.

I tried restarting the container and got this:

[2025-11-05 23:54:57] [WARN] Failed to start MP4 recording for stream: Kitchen
[2025-11-05 23:54:57] [WARN] Failed to start HLS streaming for stream: Kitchen

My public port 8080 is in use by another docker container.  I tried using 8081 instead of my Traefik proxy and still get same webrtc end point 404 error.

After restart, new recordings are not being created.

I created a "test" stream, but that did not seem to change anything.
Actually, "test" started creating recordings.  I'll shut it all back down for now, but if you want me to start up and see if "test" is still working, let me know.

**Comment by matteius** [comment]
Hmmm, could you shut it all down and make sure you don't; have a different go2rtc process already running?

**Comment by matteius** [comment]
Is this still an issue on latest container or version?

**Comment by matteius** [comment]
We can re-open if still issues exist with latest build -- or better would be open a new specific issue at that time.
